version: 2.1
executors:
  default:
    docker:
      - image: circleci/golang:1.14-node

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - run: make check-style

  test:
    executor:
      name: default
    steps:
      - checkout
      - run: make test

  build:
    executor:
      name: default
    steps:
      - checkout
      - run: make dist
      - store_artifacts:
          path: dist/com.mattermost.wrangler-0.6.1.tar.gz
          destination: com.mattermost.wrangler-0.6.1.tar.gz
      

workflows:
  version: 2
  untagged-build:
    jobs:
      - build:
        filters:
          branches:
            only:
              - force-channel
      #- lint:
      #  filters:
      #    branches:
      #      only:
      #        - force-channel
      #- test:
      #  filters:
      #    branches:
      #      only:
      #        - force-channel

